import { useState } from 'react'
import './TodoTab.css'

export interface TodoItem {
  id: string
  text: string
  completed: boolean
  createdAt: string
}

interface TodoTabProps {
  todos: TodoItem[]
  onAddTodo: (text: string) => void
  onToggleTodo: (id: string) => void
  onDeleteTodo: (id: string) => void
}

export function TodoTab({ todos, onAddTodo, onToggleTodo, onDeleteTodo }: TodoTabProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [newTodoText, setNewTodoText] = useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (newTodoText.trim()) {
      onAddTodo(newTodoText.trim())
      setNewTodoText('')
    }
  }

  return (
    <div className={`todo-tab ${isExpanded ? 'expanded' : 'minimized'}`}>
      <div className="todo-tab-header" onClick={() => setIsExpanded(!isExpanded)}>
        <span>📝 To-Do List ({todos.filter(t => !t.completed).length})</span>
        <button className="todo-tab-toggle">
          {isExpanded ? '−' : '+'}
        </button>
      </div>

      {isExpanded && (
        <div className="todo-tab-content">
          <form onSubmit={handleSubmit} className="todo-input-form">
            <input
              type="text"
              value={newTodoText}
              onChange={(e) => setNewTodoText(e.target.value)}
              placeholder="Add a new task..."
              className="todo-input"
            />
            <button type="submit" className="todo-add-btn">Add</button>
          </form>

          <div className="todo-list">
            {todos.length === 0 ? (
              <div className="todo-empty">No tasks yet. Add one above!</div>
            ) : (
              todos.map(todo => {
                const isAutoGenerated = todo.id.startsWith('app-')
                return (
                  <div key={todo.id} className={`todo-item ${todo.completed ? 'completed' : ''} ${isAutoGenerated ? 'auto-generated' : ''}`}>
                    <input
                      type="checkbox"
                      checked={todo.completed}
                      onChange={() => onToggleTodo(todo.id)}
                      className="todo-checkbox"
                    />
                    <span className="todo-text">
                      {isAutoGenerated && <span className="auto-badge">📋 </span>}
                      {todo.text}
                    </span>
                    <button
                      onClick={() => onDeleteTodo(todo.id)}
                      className="todo-delete-btn"
                      title={isAutoGenerated ? "Auto-managed deadline" : "Delete task"}
                    >
                      ×
                    </button>
                  </div>
                )
              })
            )}
          </div>
        </div>
      )}
    </div>
  )
}
